ToDoList/TODOSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ToDoApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ToDoList/', include('ToDoApp.urls'), name="index"),

]
urlpatterns += staticfiles_urlpatterns()

ToDoList/ToDoApp/urls.py
from django.urls import path
from . import views

app_name = 'Todourls'
urlpatterns = [

    path('', views.index, name='index'),
    path('AddItem/', views.AddItem, name='AddItem'),
    path('DeleteItem/<int:todo_list>/', views.DeleteItem, name='Delete'),
    path('AddItempage/', views.AddItem, name='AddItempage'),
    path('EditItem/<int:todo_list>/', views.EditItem, name='Edit'),
    path('UpdateItem/<int:todo_list>/', views.UpdateItem, name='Update'),
]

ToDoList/ToDoApp/models.py
from django.db import models


# Create your models here.

class Todolist(models.Model):
    list_id = models.AutoField(primary_key=True)
    created_date = models.DateTimeField()
    text = models.CharField(max_length=2048)

    def __str__(self):
        return self.text

ToDoList/ToDoApp/forms.py
from django import forms
from . import models


class CreateList(forms.ModelForm):
    class Meta:
        model = models.Todolist
        fields = ['text']

ToDoList/ToDoApp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Todolist
from django.utils import timezone
from datetime import datetime
from django.contrib import messages


# Create your views here.

def index(request):
    TodaData = Todolist.objects.all()
    return render(request, 'Index.html', {'TodaData': TodaData})
    # return HttpResponse("haoooo")


def AddItem(request):
    if request.method == "POST":
        currentdate = timezone.now()
        txtdata = request.POST["content"]
        Todolist.objects.create(created_date=currentdate, text=txtdata)
        return render(request, 'Add.html', {'msg': 'Succesfully Inserted the Item'})
        # return messages.success(request,'Add.html','Succesfully Inserted the Item')
        # return HttpResponse('<h1> Successfully Created</h1>')
        # return HttpResponseRedirect("/ToDoList/")
    return render(request, 'Add.html', )


def DeleteItem(request, todo_list):
    Todolist.objects.get(list_id=todo_list).delete()
    return HttpResponseRedirect("/ToDoList/")


def EditItem(request, todo_list):
    dataedit = Todolist.objects.get(list_id=todo_list)
    return render(request, 'Details.html', {'dataedit': dataedit})


def UpdateItem(request, todo_list):
    if request.method == 'POST':
        currentdate = timezone.now()
        txtdata = request.POST["content"]
        print(txtdata)
        Todolist.objects.filter(list_id=todo_list).update(created_date=currentdate, text=txtdata)
        # Todolist.objects.create(created_date=currentdate, text=txtdata)
        # Todolist.objects.select_for_update(created_date=currentdate, text=txtdata).filter(list_id=todo_list)
        # Todolist.objects.get(list_id=todo_list).update_or_create(created_date=currentdate, text=txtdata)
        return HttpResponseRedirect("/ToDoList/")
    return HttpResponseRedirect("/ToDoList/")

ToDoList/ToDoApp/templates/Add.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-10">
        <form class="form-inline" method="POST" action="{% url  'Todourls:AddItem' %}">
            {% csrf_token %}
            <input type="text" class="form-control mb-2 col-md-5" name="content" id="inlineFormInputName2" placeholder="EnterToDo List Item">
            &nbsp;<button type="submit" class="btn btn-primary mb-2">Add Item</button>

        </form>

        {{msg}}

    </div>
</div>



{% endblock%}

ToDoList/ToDoApp/templates/Details.html
{% extends 'base.html' %}

{% block content %}

<div class="container" style="margin-top:5%">
     <form action="{% url 'Todourls:Update' dataedit.list_id %}" method="POST">
         {% csrf_token %}
    <div class="row justify-content-center align-items-center">
       <strong>Text:</strong> <input type="text" class="mb-2 col-md-5" name="content" id="inlineFormInputName2" value="{{dataedit.text}}">
    </div>
    <div class="row justify-content-center align-items-center">
        <strong>Modified Date:</strong>{{dataedit.created_date}}
     </div>
     <div class="row justify-content-center align-items-center">

              <button type="submit" class="btn btn-primary mb-2">Update</button>


     </div>
               </form>

</div>





{% endblock%}

ToDoList/ToDoApp/templates/Index.html
{% extends 'base.html' %}

{% block content %}
<!--<div class="divTt">fsfdfsdf gtretertertr</div>-->
<div class="row">
    <div class="col-md-10">
<!--        <form class="form-inline" method="POST" action="{% url  'Todourls:AddItem' %}">-->
<!--            {% csrf_token %}-->
<!--            <input type="text" class="form-control mb-2 col-md-5" name="content" id="inlineFormInputName2" placeholder="EnterToDo List Item">-->
<!--            &nbsp;<button type="submit" class="btn btn-primary mb-2">Add Item</button>-->

<!--        </form>-->
    </div>
</div>




<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">SI.NO</th>
        <th scope="col">CREATED DATE</th>
        <th scope="col">DETAIL</th>
        <th scope="col"></th>

      </tr>
    </thead>
    <tbody>
        {% for Toda in TodaData %}
      <tr>
        <td>{{forloop.counter}} </td>
        <td> {{Toda.created_date}}</td>
        <td> {{Toda.text}}</td>
        <td>
            <form class="d-inline-block" action="{% url 'Todourls:Delete' Toda.list_id  %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" value="delete">Delete</button>
            </form>
        </td>
          <td>
               <form class="d-inline-block" action="{% url 'Todourls:Edit' Toda.list_id %}" method="POST">
                 {% csrf_token %}
                <button type="submit" style="width:100%"  class="btn btn-danger" value="edit">Edit  </button>
                 </form>
          </td>
      </tr>
      {%endfor%}
      </tbody>
</table>




{%endblock%}

ToDoList/ToDoApp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
<!--<nav class="navbar navbar-dark bg-primary">-->
    <a class="navbar-brand font-italic" href="#">
    <img src="{% static 'ToDo.png'%}" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
  <kbd>  ToDoApp</kbd>
  </a>
<!--  <a class="navbar-brand" href="#">ToDoApp</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'Todourls:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'Todourls:AddItem' %}">Add Item</a>

      </li>
     
    </ul>
<!--    <span class="navbar-text">-->
<!--      Navbar text with an inline element-->
<!--    </span>-->
  </div>
</nav>
<div class="row">


  <div class="col-lg-4">
    <div class="spinner-border text-muted"></div>
  <div class="spinner-border text-primary"></div>
  <div class="spinner-border text-success"></div>
  <div class="spinner-border text-info"></div>
  <div class="spinner-border text-warning"></div>
  <div class="spinner-border text-danger"></div>
  <div class="spinner-border text-secondary"></div>
  <div class="spinner-border text-dark"></div>
  <div class="spinner-border text-light"></div>
  </div>
  <div class="col-lg-4">
    <div class="spinner-border text-muted"></div>
  <div class="spinner-border text-primary"></div>
  <div class="spinner-border text-success"></div>
  <div class="spinner-border text-info"></div>
  <div class="spinner-border text-warning"></div>
  <div class="spinner-border text-danger"></div>
  <div class="spinner-border text-secondary"></div>
  <div class="spinner-border text-dark"></div>
  <div class="spinner-border text-light"></div>
  </div>
  <div class="col-lg-4">
    <div class="spinner-border text-muted"></div>
  <div class="spinner-border text-primary"></div>
  <div class="spinner-border text-success"></div>
  <div class="spinner-border text-info"></div>
  <div class="spinner-border text-warning"></div>
  <div class="spinner-border text-danger"></div>
  <div class="spinner-border text-secondary"></div>
  <div class="spinner-border text-dark"></div>
  <div class="spinner-border text-light"></div>
  </div>
</div>

   {% block content %}
<div class="container">

</div>
   {% endblock%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>